apiVersion: apps/v1
kind: Deployment
metadata:
  name: snat-test
spec:
  replicas: 100
  selector:
    matchLabels:
      app: snat-test
  template:
    metadata:
      labels:
        app: snat-test
    spec:
      containers:
      - name: snat-test
        image: aritratestingcorednsregistry.azurecr.io/snattest:latest
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
